import uuid
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field


class ElementMetadata(BaseModel):
    """Metadata about a DOM element relevant for LLM reasoning."""

    tag_name: str
    is_visible: bool
    is_interactive: bool
    text: Optional[str] = None
    input_type: Optional[str] = None
    role: Optional[str] = None
    aria_label: Optional[str] = None
    name: Optional[str] = None
    id_attr: Optional[str] = None
    placeholder: Optional[str] = None
    value: Optional[str] = None
    options: List[str] = Field(default_factory=list)
    # Identifies if this looks like an application submit button
    is_submit: bool = False
    is_required: bool = False
    # Field sensitivity classification
    sensitivity: Literal["NORMAL", "SENSITIVE", "AUTHENTICATION"] = "NORMAL"


class DOMElement(BaseModel):
    """Structured representation of a DOM element."""

    element_id: str  # Unique logical ID generated by PageInspector
    metadata: ElementMetadata


class PageModel(BaseModel):
    """Structured representation of the browser page."""

    snapshot_id: str
    url: str
    title: str
    elements: List[DOMElement]


class BaseBrowserAction(BaseModel):
    """Base requirements for all actions."""

    action_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    snapshot_id: Optional[str] = None


class NavigateAction(BaseBrowserAction):
    action_type: Literal["navigate"] = "navigate"
    url: str


class ClickAction(BaseBrowserAction):
    action_type: Literal["click"] = "click"
    element_id: str


class FillAction(BaseBrowserAction):
    action_type: Literal["fill"] = "fill"
    element_id: str
    text: str


class SelectOptionAction(BaseBrowserAction):
    action_type: Literal["select"] = "select"
    element_id: str
    option_value: str


class CheckAction(BaseBrowserAction):
    action_type: Literal["check"] = "check"
    element_id: str


class UncheckAction(BaseBrowserAction):
    action_type: Literal["uncheck"] = "uncheck"
    element_id: str


class UploadFileAction(BaseBrowserAction):
    action_type: Literal["upload"] = "upload"
    element_id: str
    document_id: str


class PressKeyAction(BaseBrowserAction):
    action_type: Literal["press_key"] = "press_key"
    key: str


class ScrollAction(BaseBrowserAction):
    action_type: Literal["scroll"] = "scroll"
    direction: Literal["up", "down", "top", "bottom"]


class WaitAction(BaseBrowserAction):
    action_type: Literal["wait"] = "wait"
    duration_ms: int = Field(ge=0, le=10000)


class RefreshAction(BaseBrowserAction):
    action_type: Literal["refresh"] = "refresh"


class GoBackAction(BaseBrowserAction):
    action_type: Literal["go_back"] = "go_back"


class GoForwardAction(BaseBrowserAction):
    action_type: Literal["go_forward"] = "go_forward"


# The unified type that the LLM is allowed to generate
BrowserAction = Union[
    NavigateAction,
    ClickAction,
    FillAction,
    SelectOptionAction,
    CheckAction,
    UncheckAction,
    UploadFileAction,
    PressKeyAction,
    ScrollAction,
    WaitAction,
    RefreshAction,
    GoBackAction,
    GoForwardAction,
]
