from enum import Enum


class ApplicationStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    QUALIFIED = "QUALIFIED"
    READY = "READY"
    STARTED = "STARTED"
    AUTHENTICATING = "AUTHENTICATING"
    FORM_INSPECTED = "FORM_INSPECTED"
    MAPPING_FIELDS = "MAPPING_FIELDS"
    FILLING = "FILLING"
    VALIDATING = "VALIDATING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    WAITING_FOR_CHALLENGE = "WAITING_FOR_CHALLENGE"
    PAGE_TRANSITION = "PAGE_TRANSITION"
    RECOVERING = "RECOVERING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    SUBMITTING = "SUBMITTING"
    SUBMITTED = "SUBMITTED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    REJECTED_BY_USER = "REJECTED_BY_USER"


class AgentRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class MemoryScope(str, Enum):
    GLOBAL = "GLOBAL"
    JOB_SPECIFIC = "JOB_SPECIFIC"


class MemoryProvenance(str, Enum):
    USER_CONFIRMED = "USER_CONFIRMED"
    USER_PROVIDED = "USER_PROVIDED"
    VERIFIED_DOCUMENT = "VERIFIED_DOCUMENT"
    RESUME_EXTRACTED = "RESUME_EXTRACTED"
    DOCUMENT_EXTRACTED = "DOCUMENT_EXTRACTED"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"
    LLM_SUGGESTED = "LLM_SUGGESTED"
    EXTERNAL_SOURCE = "EXTERNAL_SOURCE"


class MemoryTrustLevel(str, Enum):
    USER_CONFIRMED = "USER_CONFIRMED"
    VERIFIED_DOCUMENT = "VERIFIED_DOCUMENT"
    EXPLICIT_PROFILE = "EXPLICIT_PROFILE"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"
    LLM_INFERRED = "LLM_INFERRED"
    GENERATED = "GENERATED"


class MemoryStatus(str, Enum):
    SUGGESTED = "SUGGESTED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


class DecisionType(str, Enum):
    AUTO_FILL = "AUTO_FILL"
    SUGGEST = "SUGGEST"
    ASK_USER = "ASK_USER"
    CONFIRM = "CONFIRM"
    GENERATE = "GENERATE"
    PAUSE = "PAUSE"
    BLOCK = "BLOCK"


class JobSourceType(str, Enum):
    LINKEDIN = "LINKEDIN"
    INDEED = "INDEED"
    COMPANY_BOARD = "COMPANY_BOARD"
    GREENHOUSE = "GREENHOUSE"
    LEVER = "LEVER"
    WORKDAY = "WORKDAY"
    OTHER = "OTHER"


class EmploymentType(str, Enum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERNSHIP = "INTERNSHIP"
    FREELANCE = "FREELANCE"


class WorkMode(str, Enum):
    REMOTE = "REMOTE"
    ONSITE = "ONSITE"
    HYBRID = "HYBRID"


class BrowserActionType(str, Enum):
    NAVIGATE = "NAVIGATE"
    CLICK = "CLICK"
    TYPE = "TYPE"
    SELECT = "SELECT"
    CHECK = "CHECK"
    UNCHECK = "UNCHECK"
    UPLOAD = "UPLOAD"
    SCROLL = "SCROLL"
    WAIT = "WAIT"
    GO_BACK = "GO_BACK"
    SCREENSHOT = "SCREENSHOT"
    INSPECT = "INSPECT"


class RequirementCategory(str, Enum):
    SKILL = "SKILL"
    PROGRAMMING_LANGUAGE = "PROGRAMMING_LANGUAGE"
    FRAMEWORK = "FRAMEWORK"
    LIBRARY = "LIBRARY"
    DATABASE = "DATABASE"
    CLOUD = "CLOUD"
    ML_AI = "ML_AI"
    TOOL = "TOOL"
    EXPERIENCE = "EXPERIENCE"
    EDUCATION = "EDUCATION"
    CERTIFICATION = "CERTIFICATION"
    RESPONSIBILITY = "RESPONSIBILITY"
    LOCATION = "LOCATION"
    WORK_MODE = "WORK_MODE"
    WORK_AUTHORIZATION = "WORK_AUTHORIZATION"
    SPONSORSHIP = "SPONSORSHIP"
    COMPENSATION = "COMPENSATION"
    AVAILABILITY = "AVAILABILITY"
    YEARS_OF_EXPERIENCE = "YEARS_OF_EXPERIENCE"
    OTHER = "OTHER"


class RequirementType(str, Enum):
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
    UNKNOWN = "UNKNOWN"


class FieldRequirement(str, Enum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
    UNKNOWN = "UNKNOWN"


class FieldSensitivity(str, Enum):
    NORMAL = "NORMAL"
    SENSITIVE = "SENSITIVE"
    AUTHENTICATION = "AUTHENTICATION"
    CHALLENGE = "CHALLENGE"


class FieldType(str, Enum):
    # Identity
    FULL_NAME = "FULL_NAME"
    FIRST_NAME = "FIRST_NAME"
    MIDDLE_NAME = "MIDDLE_NAME"
    LAST_NAME = "LAST_NAME"
    PREFERRED_NAME = "PREFERRED_NAME"
    EMAIL = "EMAIL"
    PHONE = "PHONE"

    # Location
    ADDRESS = "ADDRESS"
    CITY = "CITY"
    STATE = "STATE"
    COUNTRY = "COUNTRY"
    POSTAL_CODE = "POSTAL_CODE"
    CURRENT_LOCATION = "CURRENT_LOCATION"
    PREFERRED_LOCATION = "PREFERRED_LOCATION"
    WILLING_TO_RELOCATE = "WILLING_TO_RELOCATE"

    # Professional
    CURRENT_COMPANY = "CURRENT_COMPANY"
    CURRENT_TITLE = "CURRENT_TITLE"
    PREVIOUS_COMPANY = "PREVIOUS_COMPANY"
    JOB_TITLE = "JOB_TITLE"
    YEARS_OF_EXPERIENCE = "YEARS_OF_EXPERIENCE"
    TOTAL_EXPERIENCE = "TOTAL_EXPERIENCE"
    SKILL = "SKILL"
    TECHNOLOGY = "TECHNOLOGY"
    CERTIFICATION = "CERTIFICATION"

    # Education
    UNIVERSITY = "UNIVERSITY"
    COLLEGE = "COLLEGE"
    DEGREE = "DEGREE"
    FIELD_OF_STUDY = "FIELD_OF_STUDY"
    GRADUATION_DATE = "GRADUATION_DATE"
    GPA = "GPA"

    # Work Auth
    WORK_AUTHORIZATION = "WORK_AUTHORIZATION"
    SPONSORSHIP = "SPONSORSHIP"
    VISA_STATUS = "VISA_STATUS"
    VISA_TYPE = "VISA_TYPE"

    # Compensation
    CURRENT_SALARY = "CURRENT_SALARY"
    EXPECTED_SALARY = "EXPECTED_SALARY"
    SALARY_RANGE = "SALARY_RANGE"
    CURRENCY = "CURRENCY"

    # Availability
    START_DATE = "START_DATE"
    NOTICE_PERIOD = "NOTICE_PERIOD"
    AVAILABILITY = "AVAILABILITY"

    # Questions
    MOTIVATION = "MOTIVATION"
    WHY_COMPANY = "WHY_COMPANY"
    WHY_ROLE = "WHY_ROLE"
    COVER_LETTER = "COVER_LETTER"
    ACHIEVEMENT = "ACHIEVEMENT"
    PROJECT_DESCRIPTION = "PROJECT_DESCRIPTION"
    TECHNICAL_QUESTION = "TECHNICAL_QUESTION"
    BEHAVIORAL_QUESTION = "BEHAVIORAL_QUESTION"
    CUSTOM_QUESTION = "CUSTOM_QUESTION"

    # Added for Golden ATS
    GRAD_YEAR = "GRAD_YEAR"
    CGPA = "CGPA"
    GITHUB = "GITHUB"
    PORTFOLIO = "PORTFOLIO"
    OFFICE_SNACK = "OFFICE_SNACK"
    PRIMARY_LANGUAGE = "PRIMARY_LANGUAGE"
    ML_FRAMEWORKS = "ML_FRAMEWORKS"
    LLM_EXP = "LLM_EXP"
    RAG_EXP = "RAG_EXP"
    HAS_CLOUD = "HAS_CLOUD"
    CLOUD_PLATFORM = "CLOUD_PLATFORM"
    CLOUD_EXP = "CLOUD_EXP"
    RESUME = "RESUME"

    # Demographics
    GENDER = "GENDER"
    RACE_ETHNICITY = "RACE_ETHNICITY"
    DISABILITY = "DISABILITY"
    VETERAN_STATUS = "VETERAN_STATUS"
    AGE = "AGE"
    OTHER_DEMOGRAPHIC = "OTHER_DEMOGRAPHIC"

    # Security
    PASSWORD = "PASSWORD"
    OTP = "OTP"
    TWO_FACTOR = "2FA"
    SECURITY_CODE = "SECURITY_CODE"
    AUTHENTICATION_FIELD = "AUTHENTICATION_FIELD"
    CAPTCHA = "CAPTCHA"
    ANTI_BOT_CHALLENGE = "ANTI_BOT_CHALLENGE"

    UNKNOWN = "UNKNOWN"


class HITLRequestType(str, Enum):
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    SENSITIVE_FIELD = "SENSITIVE_FIELD"
    AMBIGUOUS_FIELD = "AMBIGUOUS_FIELD"
    GENERATED_ANSWER_REVIEW = "GENERATED_ANSWER_REVIEW"
    CAPTCHA = "CAPTCHA"
    OTP = "OTP"
    TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH"
    AUTHENTICATION = "AUTHENTICATION"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    REVIEW = "REVIEW"
    APPROVAL = "APPROVAL"
    CLARIFICATION = "CLARIFICATION"


class HITLRequestStatus(str, Enum):
    PENDING = "PENDING"
    VIEWED = "VIEWED"
    RESPONDING = "RESPONDING"
    RESOLVED = "RESOLVED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class HITLResponseType(str, Enum):
    TEXT = "TEXT"
    BOOLEAN = "BOOLEAN"
    SINGLE_SELECT = "SINGLE_SELECT"
    MULTI_SELECT = "MULTI_SELECT"
    DATE = "DATE"
    NUMBER = "NUMBER"
    DOCUMENT_REFERENCE = "DOCUMENT_REFERENCE"
    APPROVAL = "APPROVAL"
    REJECTION = "REJECTION"
    CHALLENGE_COMPLETION = "CHALLENGE_COMPLETION"


class HITLApprovalScope(str, Enum):
    APPROVE_FIELD = "APPROVE_FIELD"
    APPROVE_GENERATED_ANSWER = "APPROVE_GENERATED_ANSWER"
    APPROVE_DOCUMENT = "APPROVE_DOCUMENT"
    APPROVE_REVIEW = "APPROVE_REVIEW"
    REJECT_FIELD = "REJECT_FIELD"
    REJECT_ANSWER = "REJECT_ANSWER"
    REJECT_REVIEW = "REJECT_REVIEW"


class ReviewSessionStatus(str, Enum):
    INCOMPLETE = "INCOMPLETE"
    READY = "READY"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
