"""Add HITL models

Revision ID: 0ab4f35d61a7
Revises: ce58e3a2e878
Create Date: 2026-09-18 00:02:57.591876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ab4f35d61a7"
down_revision: Union[str, Sequence[str], None] = "ce58e3a2e878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hitl_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("request_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("context_json", sa.JSON(), nullable=False),
        sa.Column("required_action", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["application_workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hitl_requests_application_id"), "hitl_requests", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_hitl_requests_user_id"), "hitl_requests", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_hitl_requests_workflow_id"), "hitl_requests", ["workflow_id"], unique=False
    )
    op.create_table(
        "hitl_approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("approval_scope", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column("decision_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_id"], ["hitl_requests.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["application_workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hitl_approvals_application_id"), "hitl_approvals", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_hitl_approvals_request_id"), "hitl_approvals", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_hitl_approvals_user_id"), "hitl_approvals", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_hitl_approvals_workflow_id"), "hitl_approvals", ["workflow_id"], unique=False
    )
    op.create_table(
        "hitl_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("response_type", sa.String(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_id"], ["hitl_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["application_workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hitl_responses_application_id"), "hitl_responses", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_hitl_responses_request_id"), "hitl_responses", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_hitl_responses_user_id"), "hitl_responses", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_hitl_responses_workflow_id"), "hitl_responses", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hitl_responses_workflow_id"), table_name="hitl_responses")
    op.drop_index(op.f("ix_hitl_responses_user_id"), table_name="hitl_responses")
    op.drop_index(op.f("ix_hitl_responses_request_id"), table_name="hitl_responses")
    op.drop_index(op.f("ix_hitl_responses_application_id"), table_name="hitl_responses")
    op.drop_table("hitl_responses")
    op.drop_index(op.f("ix_hitl_approvals_workflow_id"), table_name="hitl_approvals")
    op.drop_index(op.f("ix_hitl_approvals_user_id"), table_name="hitl_approvals")
    op.drop_index(op.f("ix_hitl_approvals_request_id"), table_name="hitl_approvals")
    op.drop_index(op.f("ix_hitl_approvals_application_id"), table_name="hitl_approvals")
    op.drop_table("hitl_approvals")
    op.drop_index(op.f("ix_hitl_requests_workflow_id"), table_name="hitl_requests")
    op.drop_index(op.f("ix_hitl_requests_user_id"), table_name="hitl_requests")
    op.drop_index(op.f("ix_hitl_requests_application_id"), table_name="hitl_requests")
    op.drop_table("hitl_requests")
    # ### end Alembic commands ###
