"""Add BrowserActionExecutionModel

Revision ID: 0cdbc590ebcc
Revises: 624b83344ddc
Create Date: 2026-09-16 02:13:16.398138

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cdbc590ebcc"
down_revision: Union[str, Sequence[str], None] = "624b83344ddc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "browser_action_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.String(length=255), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["browser_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_browser_action_executions_action_id"),
        "browser_action_executions",
        ["action_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_browser_action_executions_action_id"), table_name="browser_action_executions"
    )
    op.drop_table("browser_action_executions")
    # ### end Alembic commands ###
