"""Phase 9 Content Generation

Revision ID: 1fabb9009322
Revises: cdd63cab5d6a
Create Date: 2026-09-28 03:04:52.142372

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fabb9009322"
down_revision: Union[str, Sequence[str], None] = "cdd63cab5d6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_content",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_content_application_id"),
        "application_content",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_content_content_type"),
        "application_content",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_content_job_id"), "application_content", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_content_user_id"), "application_content", ["user_id"], unique=False
    )
    op.create_table(
        "content_generation_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("generation_version", sa.String(), nullable=False),
        sa.Column("policy_version", sa.String(), nullable=False),
        sa.Column("model_identifier", sa.String(), nullable=False),
        sa.Column("evidence_references", sa.JSON(), nullable=False),
        sa.Column("validation_result", sa.JSON(), nullable=False),
        sa.Column("decision_result", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_generation_events_application_id"),
        "content_generation_events",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_generation_events_job_id"),
        "content_generation_events",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_generation_events_user_id"),
        "content_generation_events",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "content_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("generator_version", sa.String(), nullable=False),
        sa.Column("policy_version", sa.String(), nullable=False),
        sa.Column("evidence_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["content_id"], ["application_content.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_versions_application_id"),
        "content_versions",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_versions_content_id"), "content_versions", ["content_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_versions_content_id"), table_name="content_versions")
    op.drop_index(op.f("ix_content_versions_application_id"), table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_index(
        op.f("ix_content_generation_events_user_id"), table_name="content_generation_events"
    )
    op.drop_index(
        op.f("ix_content_generation_events_job_id"), table_name="content_generation_events"
    )
    op.drop_index(
        op.f("ix_content_generation_events_application_id"), table_name="content_generation_events"
    )
    op.drop_table("content_generation_events")
    op.drop_index(op.f("ix_application_content_user_id"), table_name="application_content")
    op.drop_index(op.f("ix_application_content_job_id"), table_name="application_content")
    op.drop_index(op.f("ix_application_content_content_type"), table_name="application_content")
    op.drop_index(op.f("ix_application_content_application_id"), table_name="application_content")
    op.drop_table("application_content")
    # ### end Alembic commands ###
