"""Add phase 12 models

Revision ID: 36f87c317d34
Revises: 50d14365cfa6
Create Date: 2026-09-28 22:39:30.651241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36f87c317d34"
down_revision: Union[str, Sequence[str], None] = "50d14365cfa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unknown_question_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_fingerprint", sa.String(), nullable=False),
        sa.Column("normalized_category", sa.String(), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("applications_seen", sa.Integer(), nullable=False),
        sa.Column("companies_seen", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_frequency", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unknown_question_observations_question_fingerprint"),
        "unknown_question_observations",
        ["question_fingerprint"],
        unique=False,
    )
    op.create_table(
        "analytics_snapshots",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("metric_type", sa.String(), nullable=False),
        sa.Column("dimension", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "metric_type", "dimension", "calculated_at", name="uq_analytics_snapshot"
        ),
    )
    op.create_index(
        op.f("ix_analytics_snapshots_user_id"), "analytics_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "application_outcomes",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("outcome_type", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_outcomes_application_id"),
        "application_outcomes",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_outcomes_user_id"), "application_outcomes", ["user_id"], unique=False
    )
    op.create_table(
        "feedback_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column("feedback_type", sa.String(), nullable=False),
        sa.Column("source_entity", sa.String(), nullable=False),
        sa.Column("original_value_json", sa.JSON(), nullable=True),
        sa.Column("feedback_metadata_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_events_application_id"),
        "feedback_events",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_events_user_id"), "feedback_events", ["user_id"], unique=False
    )
    op.add_column("application_events", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "application_events", sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column("application_events", sa.Column("previous_state", sa.String(), nullable=True))
    op.add_column("application_events", sa.Column("new_state", sa.String(), nullable=False))
    op.add_column("application_events", sa.Column("actor_type", sa.String(), nullable=False))
    op.add_column("application_events", sa.Column("source", sa.String(), nullable=True))
    op.add_column("application_events", sa.Column("run_id", sa.Uuid(), nullable=True))
    op.add_column("application_events", sa.Column("queue_item_id", sa.Uuid(), nullable=True))
    op.add_column("application_events", sa.Column("correlation_id", sa.String(), nullable=False))
    op.add_column("application_events", sa.Column("reason_category", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_application_events_correlation_id"),
        "application_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_events_user_id"), "application_events", ["user_id"], unique=False
    )
    op.create_foreign_key(
        None, "application_events", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "application_events", "autonomous_runs", ["run_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None,
        "application_events",
        "application_queue_items",
        ["queue_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "application_events", type_="foreignkey")  # type: ignore
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "application_events", type_="foreignkey")  # type: ignore
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "application_events", type_="foreignkey")  # type: ignore
    op.drop_index(op.f("ix_application_events_user_id"), table_name="application_events")
    op.drop_index(op.f("ix_application_events_correlation_id"), table_name="application_events")
    op.drop_column("application_events", "reason_category")
    op.drop_column("application_events", "correlation_id")
    op.drop_column("application_events", "queue_item_id")
    op.drop_column("application_events", "run_id")
    op.drop_column("application_events", "source")
    op.drop_column("application_events", "actor_type")
    op.drop_column("application_events", "new_state")
    op.drop_column("application_events", "previous_state")
    op.drop_column("application_events", "occurred_at")
    op.drop_column("application_events", "user_id")
    op.drop_index(op.f("ix_feedback_events_user_id"), table_name="feedback_events")
    op.drop_index(op.f("ix_feedback_events_application_id"), table_name="feedback_events")
    op.drop_table("feedback_events")
    op.drop_index(op.f("ix_application_outcomes_user_id"), table_name="application_outcomes")
    op.drop_index(op.f("ix_application_outcomes_application_id"), table_name="application_outcomes")
    op.drop_table("application_outcomes")
    op.drop_index(op.f("ix_analytics_snapshots_user_id"), table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    op.drop_index(
        op.f("ix_unknown_question_observations_question_fingerprint"),
        table_name="unknown_question_observations",
    )
    op.drop_table("unknown_question_observations")
    # ### end Alembic commands ###
