"""Add idempotency constraints

Revision ID: 56b93fa6fb37
Revises: eef7b2e03b50
Create Date: 2026-09-16 00:32:12.419825

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56b93fa6fb37"
down_revision: Union[str, Sequence[str], None] = "eef7b2e03b50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_job_source_payload_source_job", "job_source_payloads", ["source_id", "source_job_id"]
    )
    op.add_column("memory_facts", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_memory_facts_content_hash"), "memory_facts", ["content_hash"], unique=False
    )
    op.create_unique_constraint(
        "uix_memory_fact_identity",
        "memory_facts",
        ["user_id", "source", "provenance", "content_hash"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_memory_fact_identity", "memory_facts", type_="unique")
    op.drop_index(op.f("ix_memory_facts_content_hash"), table_name="memory_facts")
    op.drop_column("memory_facts", "content_hash")
    op.drop_constraint("uix_job_source_payload_source_job", "job_source_payloads", type_="unique")
    # ### end Alembic commands ###
