"""Add form intelligence models

Revision ID: 5ae5e59ffebc
Revises: 0cdbc590ebcc
Create Date: 2026-09-16 12:08:07.259159

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae5e59ffebc"
down_revision: Union[str, Sequence[str], None] = "0cdbc590ebcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_forms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_page_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["browser_sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_forms_application_id"),
        "application_forms",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_forms_session_id"), "application_forms", ["session_id"], unique=False
    )
    op.create_table(
        "application_form_fields",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("element_id", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("field_data_json", sa.JSON(), nullable=False),
        sa.Column("classification_type", sa.String(), nullable=True),
        sa.Column("sensitivity", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["form_id"], ["application_forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_form_fields_element_id"),
        "application_form_fields",
        ["element_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_form_fields_form_id"),
        "application_form_fields",
        ["form_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_form_fields_snapshot_id"),
        "application_form_fields",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "field_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("decision_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("memory_ids_json", sa.JSON(), nullable=False),
        sa.Column("proposed_action_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["application_form_fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_decisions_decision_type"), "field_decisions", ["decision_type"], unique=False
    )
    op.create_index(
        op.f("ix_field_decisions_field_id"), "field_decisions", ["field_id"], unique=False
    )
    op.create_table(
        "generated_answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_used", sa.String(), nullable=False),
        sa.Column("generated_text", sa.String(), nullable=False),
        sa.Column("source_memory_ids_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["application_form_fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_answers_application_id"),
        "generated_answers",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_answers_field_id"), "generated_answers", ["field_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_answers_field_id"), table_name="generated_answers")
    op.drop_index(op.f("ix_generated_answers_application_id"), table_name="generated_answers")
    op.drop_table("generated_answers")
    op.drop_index(op.f("ix_field_decisions_field_id"), table_name="field_decisions")
    op.drop_index(op.f("ix_field_decisions_decision_type"), table_name="field_decisions")
    op.drop_table("field_decisions")
    op.drop_index(
        op.f("ix_application_form_fields_snapshot_id"), table_name="application_form_fields"
    )
    op.drop_index(op.f("ix_application_form_fields_form_id"), table_name="application_form_fields")
    op.drop_index(
        op.f("ix_application_form_fields_element_id"), table_name="application_form_fields"
    )
    op.drop_table("application_form_fields")
    op.drop_index(op.f("ix_application_forms_session_id"), table_name="application_forms")
    op.drop_index(op.f("ix_application_forms_application_id"), table_name="application_forms")
    op.drop_table("application_forms")
    # ### end Alembic commands ###
