"""Add JobSourcePayload and matching_version

Revision ID: 82f70d43086e
Revises: a86c6ed8926a
Create Date: 2026-09-15 21:36:55.640681

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82f70d43086e"
down_revision: Union[str, Sequence[str], None] = "a86c6ed8926a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_source_payloads",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_job_id", sa.String(), nullable=False),
        sa.Column("payload_hash", sa.String(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["job_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_source_payloads_payload_hash"),
        "job_source_payloads",
        ["payload_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_source_payloads_source_id"), "job_source_payloads", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_source_payloads_source_job_id"),
        "job_source_payloads",
        ["source_job_id"],
        unique=False,
    )
    op.add_column("job_match_scores", sa.Column("matching_version", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_match_scores", "matching_version")
    op.drop_index(op.f("ix_job_source_payloads_source_job_id"), table_name="job_source_payloads")
    op.drop_index(op.f("ix_job_source_payloads_source_id"), table_name="job_source_payloads")
    op.drop_index(op.f("ix_job_source_payloads_payload_hash"), table_name="job_source_payloads")
    op.drop_table("job_source_payloads")
    # ### end Alembic commands ###
