"""audit schema updates

Revision ID: a86c6ed8926a
Revises: 2515dc911065
Create Date: 2026-09-15 20:25:23.816238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a86c6ed8926a"
down_revision: Union[str, Sequence[str], None] = "2515dc911065"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_match_scores",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_match_scores_job_id"), "job_match_scores", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_match_scores_user_id"), "job_match_scores", ["user_id"], unique=False
    )
    op.add_column("applications", sa.Column("form_data_snapshot", sa.JSON(), nullable=True))
    op.add_column("jobs", sa.Column("extracted_requirements", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "extracted_requirements")
    op.drop_column("applications", "form_data_snapshot")
    op.drop_index(op.f("ix_job_match_scores_user_id"), table_name="job_match_scores")
    op.drop_index(op.f("ix_job_match_scores_job_id"), table_name="job_match_scores")
    op.drop_table("job_match_scores")
    # ### end Alembic commands ###
