"""Add application_id to browser sessions

Revision ID: cdd63cab5d6a
Revises: decdd0cfd34a
Create Date: 2026-09-28 00:17:08.128223

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdd63cab5d6a"
down_revision: Union[str, Sequence[str], None] = "decdd0cfd34a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("browser_sessions", sa.Column("application_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "browser_sessions", "applications", ["application_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_browser_sessions_application_id_applications", "browser_sessions", type_="foreignkey"
    )
    op.drop_column("browser_sessions", "application_id")
    # ### end Alembic commands ###
