"""Add phase 3d models

Revision ID: ce58e3a2e878
Revises: 5ae5e59ffebc
Create Date: 2026-09-16 13:04:02.560643

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce58e3a2e878"
down_revision: Union[str, Sequence[str], None] = "5ae5e59ffebc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("browser_session_id", sa.UUID(), nullable=True),
        sa.Column("current_page_index", sa.Integer(), nullable=False),
        sa.Column("validation_errors_json", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["browser_session_id"], ["browser_sessions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_workflows_application_id"),
        "application_workflows",
        ["application_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_application_workflows_browser_session_id"),
        "application_workflows",
        ["browser_session_id"],
        unique=False,
    )
    op.create_table(
        "approval_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=True),
        sa.Column("approval_scope", sa.String(), nullable=False),
        sa.Column("approved_data_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["decision_id"], ["field_decisions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_records_application_id"),
        "approval_records",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_records_decision_id"), "approval_records", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_records_user_id"), "approval_records", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_records_user_id"), table_name="approval_records")
    op.drop_index(op.f("ix_approval_records_decision_id"), table_name="approval_records")
    op.drop_index(op.f("ix_approval_records_application_id"), table_name="approval_records")
    op.drop_table("approval_records")
    op.drop_index(
        op.f("ix_application_workflows_browser_session_id"), table_name="application_workflows"
    )
    op.drop_index(
        op.f("ix_application_workflows_application_id"), table_name="application_workflows"
    )
    op.drop_table("application_workflows")
    # ### end Alembic commands ###
