"""Phase 4 matching models

Revision ID: decdd0cfd34a
Revises: 0d50f7c45dc6
Create Date: 2026-09-27 21:19:56.842928

"""

from typing import Sequence, Union

import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "decdd0cfd34a"
down_revision: Union[str, Sequence[str], None] = "0d50f7c45dc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_match_scores", sa.Column("scoring_config_version", sa.String(), nullable=False)
    )
    op.add_column("job_match_scores", sa.Column("embedding_model", sa.String(), nullable=True))
    op.add_column("job_match_scores", sa.Column("embedding_version", sa.String(), nullable=True))
    op.add_column(
        "job_match_scores", sa.Column("candidate_profile_version", sa.String(), nullable=True)
    )
    op.add_column("job_match_scores", sa.Column("job_content_hash", sa.String(), nullable=True))
    op.add_column(
        "jobs", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True)
    )
    op.add_column("jobs", sa.Column("embedding_model", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("embedding_dimension", sa.Integer(), nullable=True))
    op.add_column("jobs", sa.Column("embedding_version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "embedding_version")
    op.drop_column("jobs", "embedding_dimension")
    op.drop_column("jobs", "embedding_model")
    op.drop_column("jobs", "embedding")
    op.drop_column("job_match_scores", "job_content_hash")
    op.drop_column("job_match_scores", "candidate_profile_version")
    op.drop_column("job_match_scores", "embedding_version")
    op.drop_column("job_match_scores", "embedding_model")
    op.drop_column("job_match_scores", "scoring_config_version")
    # ### end Alembic commands ###
