"""Add fingerprint and content hash to Jobs and canonical_job_id to JobSourcePayload

Revision ID: eef7b2e03b50
Revises: 82f70d43086e
Create Date: 2026-09-15 21:50:51.267075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eef7b2e03b50"
down_revision: Union[str, Sequence[str], None] = "82f70d43086e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_source_payloads", sa.Column("canonical_job_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_job_source_payloads_canonical_job_id"),
        "job_source_payloads",
        ["canonical_job_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "job_source_payloads", "jobs", ["canonical_job_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("jobs", sa.Column("fingerprint_hash", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(op.f("ix_jobs_content_hash"), "jobs", ["content_hash"], unique=False)
    op.create_index(op.f("ix_jobs_fingerprint_hash"), "jobs", ["fingerprint_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_fingerprint_hash"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_content_hash"), table_name="jobs")
    op.drop_column("jobs", "content_hash")
    op.drop_column("jobs", "fingerprint_hash")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "job_source_payloads", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_index(op.f("ix_job_source_payloads_canonical_job_id"), table_name="job_source_payloads")
    op.drop_column("job_source_payloads", "canonical_job_id")
    # ### end Alembic commands ###
